FROM ubuntu

RUN apt update
RUN apt install sudo -y
RUN groupadd bin_exec
RUN useradd -p test1 -s /bin/bash user1 -p test1 -s /bin/bash
RUN useradd -p test2 -s /bin/bash user2
RUN usermod -aG sudo,bin_exec user1
RUN usermod -aG sudo,bin_exec user2

RUN mkdir /test_bin
RUN chown -R user1:bin_exec /test_bin

COPY test1 /test_bin/test1

ENTRYPOINT [ "sleep", "604800" ]