FROM ubuntu

RUN apt update
RUN apt install sudo -y
RUN groupadd bin_exec
RUN useradd user1 
RUN useradd user2
RUN usermod -aG sudo,bin_exec user1
RUN usermod -aG sudo,bin_exec user2

RUN mkdir /test_bin
RUN chown -R user1:bin_exec /test_bin

USER user1

COPY test1 /test_bin/test1

RUN chmod +x /test_bin/test1

ENTRYPOINT [ "echo", "Hello World!" ]