apiVersion: v1
kind: Pod
metadata:
  name:  binexec
  labels:
    app: binexec
  namespace: kubesec-demo
spec:
  containers:
  - image: devsecopscloset/bin_exec_vuln_pod
    imagePullPolicy: Always
    name:  binexec
  restartPolicy: Always