apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rmi-ldap-block
  namespace: kubesec-demo
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: log4j-vuln-pod
  egress:
      - ports: 
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 8080
          - protocol: TCP
            port: 443
          - protocol: UDP
            port: 80
          - protocol: UDP
            port: 8080
          - protocol: UDP
            port: 443