apiVersion: v1
kind: Pod
metadata:
  name: log4j-app
  labels:
    app: log4j-vuln-pod
  namespace: kubesec-demo
spec:
  containers:
  - image: ghcr.io/christophetd/log4shell-vulnerable-app
    imagePullPolicy: IfNotPresent
    name: log4shell-vulnerable-app
    ports:
      - containerPort: 8080
  restartPolicy: Always
  