apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-cve-2019-14287-sudo-privilege-escalation
  namespace: default
spec:
  tags: ["CVE", "Sudo-Privilege-Escalation", "CVE-2019-14287"]
  message: "Alert! Non Root User Tried to Run sudo Command"
  selector:
    matchLabels:
      pod: testpod   #change this label with your label
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/sudo
      ownerOnly: true
    - path: /bin/sudo
      ownerOnly: true
    action: Block