apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: sudo-privilege-escalation
  namespace: kubesec-demo
spec:
  tags: ["CVE", "Sudo-Privilege-Escalation", "CVE-2019-14287"]
  message: "Alert! Non Root User Tried to Run sudo Command"
  selector:
    matchLabels:
      app: sudovuln   #change this label with your label
  process:
    severity: 5
    matchPaths:
    - path: /usr/bin/sudo
      ownerOnly: true
    - path: /bin/sudo
      ownerOnly: true
    action: Block